version: "3"

services:
#  nginx:
#    image: nginx
#    volumes:
#      - ./docker/nginx/:/etc/nginx/conf.d/
#    networks:
#      - front
#      - backend
#    ports:
#      - 8080:80
#  phpunit:
#    image: "phpunit/phpunit"
#    volumes:
#      - ./:/var/www/

  mysql:
    image: "mysql:5.7"
    volumes:
      - ./docker/db:/var/lib/mysql/
#      - ./run/mysqld/:/var/run/mysqld/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sovet
      MYSQL_USER: sovet
      MYSQL_PASSWORD: pass
    ports:
      - 3306:3306

  apache:
    build: ./docker/apache
    volumes:
      - ./:/var/www/
#      - ./run/:/var/run/
    depends_on:
      - mysql
    ports:
      - "8080:80"