version: "3"
services:
  apache:
    build: ./docker/apache
    container_name: sovet_www
    volumes:
      - .:/var/www
      - ./docker/apache/php.ini:/usr/local/etc/php.ini
    ports:
      - 8080:80
    networks:
      - backend

  db_mysql:
    image: mysql:5.7
    container_name: sovet_db
    volumes:
      - ./docker/db:/var/lib/mysql/
#    command: --init-file /var/lib/mysql/sovet.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sovet
      MYSQL_USER: sovet
      MYSQL_PASSWORD: pass
    networks:
      - backend
    ports:
      - 3306:3306

  webpack:
    build: docker/nodejs
    container_name: sovet_node
    ports:
      - 80:4000
    volumes:
      - ./html:/usr/src/app/:rw
    environment:
      - NODE_ENV=dev

networks:
    backend:
